### ISSUE TITLE
haa?

### ISSUE THREAD

**Issue by SAV-404** [NuclearC/agar.io-v72#1]
i was waiting for this moment a long time...we all love v72..but you know the logic is so bad...why not taking the newest versions of agario..like protocol 11 for example..i mean the retina quality makes the game more vanilla and awesome.....i tried to use the october version and it works for a while..cz miniclip did an update for the game so it cause an issue for the older versions.. i hope there is a solution of that!

**Comment by freaky767** [comment]
v72>all

**Comment by freaky767** [comment]
WHY THE THUMBS DOWN?1?!

**Comment by SAV-404** [comment]
you're not even helping!!
