### ISSUE TITLE
not work...

### ISSUE THREAD

**Issue by DeadLord1337** [NuclearC/agar.io-v72#2]
Unable to access the website

Can't find DNS address of server c.
![image](https://user-images.githubusercontent.com/24901742/34491802-f250ebd4-eff5-11e7-9916-6d373d447e90.png)

**Comment by DeadLord1337** [comment]
sorry work is stupid ahah (i not install npm lol)

**Comment by DeadLord1337** [comment]
![image](https://user-images.githubusercontent.com/24901742/34492047-fa1aafb6-eff6-11e7-87bd-6b1f9a399268.png)

**Comment by NuclearC** [comment]
read the resource overriding part
